// ── HOW TO EDIT ─────────────────────────────────────────────
// This is the only file you touch to change what the Face Study generates.
//
// The page stitches the chosen options into ONE flowing description, e.g.
//   "A late 20s, sharp and impatient highland folk — a heart-shaped face
//    with a soft, narrow jaw; hooded, wide-set eyes; ... and freckled skin."
//
// So write each option as a little sentence fragment, not a bare label:
//   • context options → drop into "A {age}, {temperament} {heritage}"
//       age/heritage read as the person ("late 20s", "highland folk").
//       Keep them lowercase — they sit mid-sentence.
//   • feature options → read as a noun phrase you could list after "with"
//       ("a heart-shaped face with a soft, narrow jaw", "hooded, wide-set eyes").
//
// • Add a new option: add a fragment string to that trait's `options` array.
//   (Use "double quotes" for any fragment containing an apostrophe.)
// • Add a whole new trait: copy a block below and change id / label / options.
//     phase: 'context'  → the "who", shown up front so you know the person.
//     phase: 'feature'  → a facial feature revealed one-at-a-time on the timer,
//                         in the order it appears in this array.
// That's it — the page picks everything up automatically.
// ────────────────────────────────────────────────────────────

export const TRAITS = [
  {
    id: 'age',
    label: 'Age',
    phase: 'context',
    options: [
      'barely eighteen',
      'early 20s',
      'mid 20s',
      'late 20s',
      'early 30s',
      'mid 30s',
      'late 30s',
      'early 40s',
      'late 40s',
      'early 50s',
      'mid 50s',
      'late 50s',
      'greying 60s',
      'weathered 70s',
      'spry 80s',
    ],
  },
  {
    id: 'temperament',
    label: 'Temperament',
    phase: 'context',
    options: [
      'weary optimist',
      'sharp and impatient',
      'guarded but curious',
      'warm and easily amused',
      'quiet and watchful',
      'restless, always half-leaving',
      'stubborn and slow to trust',
      'gentle with a temper underneath',
      'sly and quick-witted',
      'melancholy and dreaming',
      'brash and loud',
      'calm to the point of cold',
      'anxious, eager to please',
      'proud and unbending',
      'mischievous, half-smiling',
    ],
  },
  {
    id: 'heritage',
    label: 'Heritage',
    phase: 'context',
    // fantasy-leaning, broad flavour cue — each reads as the person mid-sentence.
    options: [
      'highland folk',
      'coastal seafolk',
      'desert nomad',
      'northern woodsfolk',
      'wicked witch',
      'kind goblin',
      'wandering bard',
      'quiet scholar',
      'river-valley farmer',
      'city guttersnipe',
      'retired sellsword',
      'hedge witch',
      'mountain hermit',
      'travelling merchant',
      'exiled noble',
    ],
  },
  {
    id: 'faceShape',
    label: 'Face shape',
    phase: 'feature',
    options: [
      'a heart-shaped face with a soft, narrow jaw',
      'a square face with a heavy jaw',
      'a long, oval face with high cheekbones',
      'a round, full-cheeked face',
      'an angular face with sharp cheekbones',
      'a broad forehead tapering to a small chin',
      'a diamond face, widest at the cheeks',
      'a soft, slightly jowled face',
      'a narrow, drawn face',
      'a wide, flat face',
      'an oval face with a rounded chin',
      'a bony, hollow-cheeked face',
      'a square face softened at the edges',
      'a long face with a pointed chin',
      'a broad, moon-round face',
    ],
  },
  {
    id: 'eyebrows',
    label: 'Eyebrows',
    phase: 'feature',
    options: [
      'thick, straight, low-set brows',
      'thin, high-arched brows',
      'bushy, unruly brows',
      'sparse, barely-there brows',
      'sharp, angular brows',
      'soft, rounded, close-set brows',
      'brows with an old scar through one',
      'long, feathered brows',
      'faint, pale brows',
      'dark, heavy brows nearly meeting',
      'one brow perpetually raised',
      'short, comma-shaped brows',
      'neat, carefully groomed brows',
      'wiry brows flecked with grey',
      'thin brows angled sharply down',
    ],
  },
  {
    id: 'eyes',
    label: 'Eyes',
    phase: 'feature',
    options: [
      'hooded, wide-set eyes',
      'almond, deep-set eyes',
      'large, round eyes set close together',
      'narrow eyes with a slight upward tilt',
      'downturned, tired-looking eyes',
      'small, sharp, quick eyes',
      'wide, heavy-lidded eyes',
      'uneven eyes, one set a little lower',
      'bright, restless eyes',
      'pale, watery eyes',
      'dark, unreadable eyes',
      'round, childlike eyes',
      'slanted, catlike eyes',
      'deep-set eyes ringed with shadow',
      'mismatched eyes, two colours',
    ],
  },
  {
    id: 'nose',
    label: 'Nose',
    phase: 'feature',
    options: [
      'an aquiline nose with a high bridge',
      'a small, upturned nose',
      'a broad nose with a rounded tip',
      'a long, straight nose',
      'a crooked nose, broken once',
      'a soft, rounded button nose',
      'a wide nose with flared nostrils',
      'a narrow nose with a slight bump',
      'a Roman nose with a proud arch',
      'a flat, wide-bridged nose',
      'a sharp, pointed nose',
      'a bulbous, reddened nose',
      'a delicate, tapering nose',
      'a snub nose dusted with freckles',
      'a long nose that dips at the tip',
    ],
  },
  {
    id: 'mouth',
    label: 'Mouth',
    phase: 'feature',
    options: [
      'full lips with a slight downturn',
      'a thin, wide mouth',
      'a small, softly pursed mouth',
      'a crooked half-smile',
      'a wide mouth framed by deep laugh lines',
      'a thin upper lip over a fuller lower one',
      'a mouth set in a firm line',
      'a slightly gap-toothed smile',
      'a small, tight mouth',
      'a broad, generous smile',
      'lips chapped and often bitten',
      'a lopsided, teasing grin',
      'a soft, neutral mouth',
      'thin lips pressed pale',
      "a wide mouth with a pronounced cupid's bow",
    ],
  },
  {
    id: 'hair',
    label: 'Hair',
    phase: 'feature',
    options: [
      'tight coils cropped close',
      'a straight, chin-length bob',
      'long, wavy hair tied back',
      'thinning hair combed over',
      'wild, curly, shoulder-length hair',
      'shaved sides under a tousled top',
      'hair braided and coiled up',
      'fine, wispy, greying hair',
      'a shaved head with faint stubble',
      'a long grey braid down the back',
      'a messy topknot',
      'short, spiky, dyed hair',
      'loose ringlets framing the face',
      'lank hair hanging in the eyes',
      'a receding hairline, close-cropped',
    ],
  },
  {
    id: 'skin',
    label: 'Skin',
    phase: 'feature',
    options: [
      'freckled, weathered skin',
      'smooth skin with a faint scar over one brow',
      'sun-worn skin with deep laugh lines',
      'clear skin scattered with moles',
      'ruddy across the cheeks and nose',
      'pale skin with fine, visible veins',
      'a lined forehead and a calloused look',
      'a birthmark trailing along the jaw',
      'olive skin, smooth and even',
      'dark skin with a warm undertone',
      'sallow, sun-starved skin',
      'skin dotted with old acne scars',
      'a faded tattoo along one cheek',
      'windburned, ruddy skin',
      'porcelain skin that flushes easily',
    ],
  },
]
