// ── HOW TO EDIT ─────────────────────────────────────────────
// This is the only file you touch to change what the Fortune Teller says.
//
// It's just a flat list of strings. The page picks ONE at random after the
// (completely pointless) loading screen. The question you typed is ignored —
// that's the joke.
//
// • Add a fortune: add a string to the FORTUNES array.
// • Remove one: delete its line.
// • Keep them short-ish so they read well on one card.
//
// Tone is a mix of earnest oracle, absurd, and deadpan — feel free to lean
// however you like. Order doesn't matter (selection is random).
// ────────────────────────────────────────────────────────────

export const FORTUNES = [
  'The answer is yes, but the timing is comedic.',
  'Someone is thinking about you. It is your dentist.',
  'A great opportunity approaches. It will be wearing a disguise.',
  'You will find what you lost the moment you stop needing it.',
  'The stars are aligned. Unfortunately, they are aligned for someone else.',
  'Say the thing you have been rehearsing in the shower.',
  'A door closes. A slightly nicer door opens down the hall.',
  'Your patience will be rewarded. Not soon, but rewarded.',
  'The universe says: check your other pocket.',
  'You are closer than you think, and further than you hoped.',
  'Trust the plan, even though there is no plan.',
  'A small kindness today will echo louder than you expect.',
  'The thing you are avoiding is not as bad as the avoiding.',
  'Rain is coming. Bring the umbrella you will forget anyway.',
  'You will laugh about this. Give it eighteen months.',
  'Beware of Tuesdays wearing the costume of Mondays.',
  'The crystal ball is foggy, but it likes your vibe.',
  'What you seek is also seeking you, and it is running late.',
  'Money is coming. It will arrive and leave through the same door.',
  'An old friend will surface. Let them.',
  'The path forward is unclear because you keep closing your eyes.',
  'Yes. Absolutely. Probably. Ask again in an hour.',
  'A stranger will give you excellent advice you will ignore.',
  'The number seven is significant. We do not know why.',
  'You will make the right choice by accidentally making the wrong one first.',
  'Something you wrote long ago will find its reader.',
  'Do not lend your favorite pen this week.',
  'The future is bright, so consider sunglasses.',
  'A nap is not procrastination if the oracle prescribes it.',
  'Your instincts are correct. Your second-guessing is not.',
  'Great change begins with a very small snack.',
  'The bridge you fear to cross has already been inspected.',
  'You will receive a message that changes everything, or nothing.',
  'Plant the seed now; the harvest gossips about you later.',
  'A grudge you are holding is holding you back — and it is heavy.',
  'The door is locked, but you have been pushing a pull door.',
  'Luck favors you today. Do not test how much.',
  'Someone underestimates you. Enjoy the advantage.',
  'The thing you practiced in your head will go better out loud.',
  'You are exactly one brave sentence away from a better week.',
  'A coin you drop will roll somewhere delightful.',
  'The oracle sees pasta in your near future. This is good.',
  'What feels like an ending is a very dramatic intermission.',
  'You will win an argument you did not know you were having.',
  'Do the boring task first; the fun one tastes better after.',
  'A compliment is coming. Accept it without arguing.',
  'The map is wrong, but your feet know the way.',
  'Somewhere, a plan is coming together in your favor.',
  'Beware the second cup of coffee after 4pm. The oracle warned you.',
  'You will be right, but not in the way you wanted to be.',
  'Say yes to the odd invitation.',
  'The knot untangles when you stop yanking it.',
  'A creative idea is circling. Leave a window open.',
  'Your future self says thank you for what you do today.',
  'The quiet person in the room has the answer you need.',
  'Fortune smiles upon you. It also has spinach in its teeth.',
  'You will finish the thing. Yes, that thing.',
  'A detour will show you the better road.',
  'Rest is not a reward you must earn. Take it.',
  'The email you are dreading will be shorter than the dread.',
  'Something lost between the couch cushions returns to you.',
  'You will be tempted to explain yourself. Do not bother.',
  'The oracle predicts weather. It will happen outside.',
  'A risk taken gently is still a risk taken.',
  'Your name will be spoken kindly in a room you are not in.',
  'The candle you light for someone else warms your own hands.',
  'Wait three days before deciding. The answer ripens.',
  "You are the plot twist in someone else's good story.",
  'A phone call you keep postponing goes better than expected.',
  'The oracle sees keys. You left them where you always leave them.',
  'Momentum is building. Do not stand in front of it.',
  'The best revenge is a really excellent sandwich.',
  'You will stumble upon exactly the right song at the right time.',
  'A closed chapter wants a proper goodbye. Give it one.',
  'Fortune is fickle, but it has a soft spot for you today.',
  'The answer you want and the answer you need are shaking hands.',
  'Do not water plants that refuse to grow. Metaphorically.',
  'A small victory today outranks a large excuse tomorrow.',
  'You will meet someone who reminds you who you are.',
  'The oracle senses a great decision made over breakfast.',
  'What you build in private will be admired in public.',
  'Let the phone ring. Whoever it is will call back.',
  'A forgotten dream resurfaces with a new outfit.',
  'You are allowed to change your mind. It is a superpower.',
  'The wind shifts in your favor around noon.',
  'Someone will hand you exactly what you dropped.',
  'The oracle predicts you will overthink this fortune. Stop.',
  'A yes today prevents a much bigger yes tomorrow. Choose wisely.',
  'Your kindness is not weakness; it is a slow-acting strength.',
  'The thing you are proud of, you should say out loud.',
  'A quiet Sunday holds a loud realization.',
  'You will finally understand the joke about a week from now.',
  'The oracle sees stairs. Take the elevator; save your knees.',
  'A tiny apology clears a very large room.',
  'What is meant for you will not require a fistfight.',
  'Your future is not written; it is being doodled, and it looks fun.',
  'A neglected houseplant forgives you and grows anyway.',
  'The right people are already walking toward you.',
  'You will dodge a mistake so smoothly no one will notice, including you.',
  'The oracle recommends water. Drink some. You know why.',
  'A stubborn problem dissolves the moment you sleep on it.',
  'Your good news is running errands but it is on its way.',
  'The next stranger you help is helping you back, later.',
  'Do not read too much into the number on the receipt.',
  'A window of luck opens Thursday. Climb through.',
  'You will remember something important at the worst possible time. Write it down now.',
  'The oracle senses new shoes and, therefore, new confidence.',
  'A hard conversation ends softer than it began.',
  'Whatever you are procrastinating takes eleven minutes. The oracle timed it.',
  'You will be given a second chance disguised as a scheduling conflict.',
  'The mirror lied this morning; you look great.',
  'A quiet talent of yours is about to become very loud.',
  'The path splits. Take the one that scares you slightly less.',
  'You will receive change you did not know you were owed.',
  'The oracle foresees a nap so good it should be illegal.',
  'Do not trust a shortcut that requires directions.',
  'A small doubt is not a stop sign; it is a speed bump.',
  'You will say the perfect thing three seconds too late. That is normal.',
  'Fortune deposits a coincidence in your account this week.',
  'The friend who owes you money is thinking about it. Progress.',
  'A tidy desk hides a messy genius. Keep going.',
  'You will find the courage between the third and fourth attempt.',
  'The oracle sees a spilled drink. It is fine. Buy the napkins.',
  'What you fear losing, you never really had a grip on. Loosen up.',
  'A gentle nudge from the universe is coming. Do not ignore the sign.',
  'You will be the calm one in a room that needs it.',
  'The oracle predicts your favorite snack is out of stock. Adapt.',
  'A decision made in kindness ages the best.',
  'You will laugh at a text at exactly the wrong meeting.',
  'The universe is buffering. Your reward will load shortly.',
  'A promise you make to yourself matters more than you admit.',
  'The oracle sees a red light that saves you from something worse.',
  'You will finish stronger than you started. You always do.',
  'A song you forgot will play and fix your whole afternoon.',
  'Do not argue with people who are enjoying being wrong.',
  'The oracle senses you double-checked the door. It is locked.',
  'A gift arrives without an occasion. Say thank you loudly.',
  'You will underestimate how much a walk helps. It helps.',
  'The thing you rushed will need doing twice. Slow down once.',
  'A cat, real or metaphorical, will judge you and be correct.',
  'You will win by simply showing up, which is harder than it sounds.',
  'The oracle predicts a plot twist in your inbox.',
  'A held breath is finally exhaled this week.',
  'Your gut and your calendar disagree. Trust the gut.',
  'The oracle sees you reaching for your phone. Put it down for ten minutes.',
  'A small brave email changes the trajectory of a month.',
  'You will be recommended for something without knowing it.',
  'The road is long, but there is snacks. There is always snacks.',
  'A worry you rehearsed will never actually happen. Refund the rehearsal.',
  'You will find the missing sock in the last place you look, obviously.',
  'The oracle foresees an unexpected compliment from an unexpected direction.',
  'What you plant in doubt still grows in the dark.',
  'A stubborn door opens if you also try lifting slightly.',
  'You will be trusted with a secret. Guard it like a dragon.',
  'The oracle sees you comparing yourself to others. Stop scrolling; start living.',
  'A late start still beats a no-start. Begin messily.',
  'Your future is knocking. It is polite, so it will wait a moment.',
  'The oracle predicts a small win you will forget to celebrate. Celebrate it.',
  'A phone at 1% will survive exactly as long as you need it to.',
  'You will meet the right idea while doing the wrong task.',
  'The oracle senses you skipped breakfast. Reconsider your life choices.',
  'A quiet no protects a loud yes later.',
  'You will be forgiven before you finish apologizing.',
  'The oracle sees confetti in your near future. Reason unknown. Enjoy.',
  "A talent you dismissed as ordinary is someone else's miracle.",
  'You will get the parking spot. The good one. Just this once.',
  'The tangled cord of your week unknots on Friday.',
  'A wild plan will work precisely because it was too silly to fear.',
  'You will be the answer to a question someone is quietly asking.',
  'The oracle recommends you finally reply to that message. You know the one.',
  'A small budget and a big idea are old friends. Introduce them.',
  'You will surprise yourself, which is the best kind of surprise.',
  'The oracle sees stairs skipped two at a time. Ambition suits you.',
  'A closed tab reopens as a fresh opportunity.',
  'You will finish the book. Maybe not that book, but a book.',
  'The universe left a note for you. It says: keep going.',
  'A grudge released this week returns as unexpected energy.',
  'You will be right on time for something you assumed you had missed.',
  'The oracle foresees leftovers that taste better on day two. Metaphor included.',
  'A brave outfit changes a timid day.',
  'You will be handed a microphone. Say the true thing.',
  'The oracle sees a green light streak. Do not question it; drive.',
  'A small savings account grows into a large peace of mind.',
  'You will win the coin toss of the week. Call heads.',
  'The oracle predicts one perfect cup of coffee. Savor it.',
  'A soft answer turns away a hard week.',
  'You will find the receipt exactly when you need to return the thing.',
  'The stars are quiet tonight, which means they are trusting you to figure it out.',
  'A dream you shelved is dusting itself off.',
  'You will get exactly one sign today. Do not ask for two.',
  'The oracle sees you rereading this. Yes, it still means yes.',
  'A generous tip returns to you as an unexpected favor.',
  'You will be the reason someone keeps going. You may never know it.',
  'The oracle senses a long-awaited yes wearing a very slow disguise.',
  'A little chaos this week rearranges into something better.',
  'You will remember why you started. Right around when you almost quit.',
  'The fog lifts. The view was worth the wait.',
  'A question you were afraid to ask answers itself kindly.',
  'You will trip, catch yourself, and look extremely cool doing it.',
  'The oracle has run out of predictions and simply believes in you.',
]

// Pick one fortune at random. Used by the Fortune Teller page.
export const randomFortune = () =>
  FORTUNES[Math.floor(Math.random() * FORTUNES.length)]
