// The playground toys — shared by the hub page and the home-page teaser.
export const PLAYGROUND_ITEMS = [
  {
    to: '/bounce-lab',
    glyph: '⬤',
    color: '#5b8def',
    title: 'Bounce Lab',
    blurb: 'Drop stuff. Drag stuff. Watch it bounce.',
  },
  {
    to: '/pixel-maker',
    glyph: '✎',
    color: '#4ecdc4',
    title: 'Pixel Maker',
    blurb: 'Paint tiny things — a small grid editor.',
  },
  {
    to: '/font-maker',
    glyph: 'Aa',
    color: '#5b8def',
    title: 'Font Maker',
    blurb: 'Draw a pixel font, letter by letter, export a real .ttf.',
  },
  {
    to: '/beat-maker',
    glyph: '♪',
    color: '#ffb800',
    title: 'Beat Maker',
    blurb: 'Tap out a loop — drums and melody.',
  },
  {
    to: '/character-maker',
    glyph: '◐',
    color: '#57b894',
    title: 'Character Maker',
    blurb: 'Build a little guy.',
  },
  {
    to: '/reference-puller',
    glyph: '◈',
    color: '#7c6cf0',
    title: 'Reference Puller',
    blurb: 'Draw from the greats.',
  },
  {
    to: '/face-study',
    glyph: '◎',
    color: '#e07a5f',
    title: 'Face Study',
    blurb: 'Draw a stranger.',
  },
  {
    to: '/fortune-teller',
    glyph: '✦',
    color: '#9d4edd',
    title: 'Fortune Teller',
    blurb: 'Ask the crystal ball.',
  },
  {
    to: '/gallery',
    glyph: '▦',
    color: '#ff6b9d',
    title: 'Gallery',
    blurb: 'What people made.',
  },
  {
    to: '/gift-package',
    glyph: '🎁',
    color: '#e0708a',
    title: 'Gift Package',
    blurb: 'Notes, a mixtape, videos, stickers — one link.',
  },
  {
    to: '/notes-wall',
    glyph: '📌',
    color: '#ffb800',
    title: 'Leave a Note',
    blurb: 'Stick a little note to the wall.',
  },
  {
    to: '/garbage-run',
    glyph: '🚛',
    color: '#f2b705',
    title: 'Garbage Run',
    blurb: "Snake, but it's a garbage truck eating bananas.",
  },
  {
    to: '/word-zap',
    glyph: '⚡',
    color: '#4ecdc4',
    title: 'Word Zap',
    blurb: 'Words fall, you type — zap them before they hit the floor.',
  },
  {
    to: '/pomodoro',
    glyph: '⏱',
    color: '#ff6b9d',
    title: 'Pomodoro',
    blurb: 'A shared timer — share the link, everyone sees the same clock.',
  },
  {
    to: '/game-of-life',
    glyph: '⊞',
    color: '#4ecdc4',
    title: 'Game of Life',
    blurb: "Conway's cells — draw a seed, run it, watch it evolve.",
  },
  {
    to: '/powder-toy',
    glyph: '⋰',
    color: '#f2b705',
    title: 'Powder Toy',
    blurb: 'Falling sand — water, fire, plants, and gunpowder fireworks.',
  },
  {
    to: '/reaction-diffusion',
    glyph: '❋',
    color: '#7c6cf0',
    title: 'Reaction–Diffusion',
    blurb: 'Two chemicals, a few numbers, endless organic patterns.',
  },
  {
    to: '/euphoria',
    glyph: '⛰',
    color: '#5b8def',
    title: 'Euphoria',
    blurb: 'A branching survival story. Cave, jungle, a village, six endings.',
  },
  {
    to: '/song-diary',
    glyph: '♫',
    color: '#57b894',
    title: 'Song Diary',
    blurb: 'One song a day — a small archive, browsable by date.',
  },
  {
    to: '/text-melody',
    glyph: '♬',
    color: '#e07a5f',
    title: 'Text Melody',
    blurb: 'Type a sentence, pick a scale, hear how the letters sound.',
  },
]
